In [16]:
import numpy as np
import time
import random
import math

Вправа 1. Вводиться число n. Вивести масив розміру n×n, в
якому по діагоналі йдуть числа від 1 до n, а інші числа дорівнюють 0.

In [17]:
n = int(input("Enter n: "))

Enter n: 5


In [18]:
start_time = time.perf_counter()

matrix_numpy = np.diag(np.arange(1, n + 1))

numpy_time = time.perf_counter() - start_time
print(matrix_numpy)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [21]:
start_time = time.perf_counter()

custom_matrix = [[i + 1 if i == j else 0 for j in range(n)] for i in range(n)]
    
custom_time = time.perf_counter() - start_time
custom_matrix = np.array(custom_matrix)
print(matrix_custom)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [23]:
print(f"Numpy time: {round(numpy_time * 1000, 3)} ms.")
print(f"Custom time: {round(custom_time * 1000, 3)} ms.")

Numpy time: 0.222 ms.
Custom time: 0.242 ms.


Вправа 2. Вводиться число n. Розставити 1 та 0 у шаховому
порядку, починаючи з 1 в матриці розміром n×n, використовуючи
слайсінг.

In [2]:
n = int(input("Enter n: "))

Enter n: 5


In [38]:
start_time = time.perf_counter()

numpy_matrix = np.zeros((n, n), dtype = int)

numpy_matrix[1::2,::2] = 1
numpy_matrix[::2,1::2] = 1

numpy_time = time.perf_counter() - start_time
print(numpy_matrix)

[[0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]]


In [39]:
start_time = time.perf_counter()
custom_matrix = arr = [[0 if not (i+j)%2 else 1 for j in range(n)] for i in range(n)]
        
custom_time = time.perf_counter() - start_time
custom_matrix = np.array(custom_matrix)
print(custom_matrix)

[[0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]]


In [40]:
print(f"Numpy time: {round(numpy_time * 1000, 3)} ms.")
print(f"Custom time: {round(custom_time * 1000, 3)} ms.")

Numpy time: 0.146 ms.
Custom time: 0.291 ms.


Вправа 4. Вводяться числа n і m. Вивести масив розміру n×m, в
якому у першому рядку (рядок з нулевим індексом) йдуть числа від 0
до m–1, а всі інші елементи матриці дорівнюють 0.

In [42]:
n = int(input("Enter n: "))
m = int(input("Enter m: "))

Enter n: 3
Enter m: 4


In [49]:
start_time = time.perf_counter()

numpy_matrix = np.zeros((n, m), dtype=int)
numpy_matrix[0] = np.arange(0, m)

numpy_time = time.perf_counter() - start_time
print(numpy_matrix)

[[0 1 2 3]
 [0 0 0 0]
 [0 0 0 0]]


In [50]:
start_time = time.perf_counter()

custom_matrix = [[j if i == 0 else 0 for j in range(m)] for i in range(n)]
    
custom_time = time.perf_counter() - start_time
custom_matrix = np.array(custom_matrix, dtype=int)
print(custom_matrix)

[[0 1 2 3]
 [0 0 0 0]
 [0 0 0 0]]


In [51]:
print(f"Numpy time: {round(numpy_time * 1000, 3)} ms.")
print(f"Custom time: {round(custom_time * 1000, 3)} ms.")

Numpy time: 0.118 ms.
Custom time: 0.182 ms.


Вправа 7. З клавіатури вводиться масив. Замінити всі нульові
елементи на –1.

In [64]:
list_str = input()
array = list(map(int, list_str.split()))
array = np.array(array)

3 4 0 6 5 0 3 0 4


In [84]:
start_time = time.perf_counter()

numpy_array = np.where(array == 0, -1, array)

numpy_time = time.perf_counter() - start_time
print(numpy_array)

[ 3  4 -1  6  5 -1  3 -1  4]


In [85]:
start_time = time.perf_counter()

custom_array = [-1 if x == 0 else x for x in array]
    
custom_time = time.perf_counter() - start_time
print(custom_array)

[3, 4, -1, 6, 5, -1, 3, -1, 4]


In [90]:
print(f"Numpy time: {round(numpy_time * 1000, 3)} ms.")
print(f"Custom time: {round(custom_time * 1000, 3)} ms.")

Numpy time: 0.156 ms.
Custom time: 0.225 ms.


Вправа 8. З клавіатури вводиться масив. Підрахувати в ньому
кількість нульових та ненульових елементів.


In [88]:
list_str = input()
array = list(map(int, list_str.split()))
array = np.array(array)

3 4 0 9 8 2 4 0 8 4 0


In [105]:
start_time = time.perf_counter()

bool_arr = (array != 0)
custom_not_zero_amount = np.count_nonzero(bool_arr)
custom_zero_amount = len(array) - custom_not_zero_amount

numpy_time = time.perf_counter() - start_time
print("Нулів:" + str(custom_zero_amount))
print("Не нулів:" + str(custom_not_zero_amount))

Нулів:3
Не нулів:8


In [106]:
start_time = time.perf_counter()

custom_not_zero_amount = len([item for item in array if item != 0])
custom_zero_amount = len([item for item in array if item == 0])
    
custom_time = time.perf_counter() - start_time
print("Нулів:" + str(custom_zero_amount))
print("Не нулів:" + str(custom_not_zero_amount))

Нулів:3
Не нулів:8


In [107]:
print(f"Numpy time: {round(numpy_time * 1000, 3)} ms.")
print(f"Custom time: {round(custom_time * 1000, 3)} ms.")

Numpy time: 0.194 ms.
Custom time: 0.212 ms.


Вправа 12. Створити масив одиниць розміром n×n та створити в
ньому «рамку», що утворюється з 0.

In [108]:
n = int(input("Enter n: "))

Enter n: 4


In [121]:
start_time = time.perf_counter()

numpy_matrix = np.ones((n, n), dtype=int)
numpy_matrix[(0, n - 1), ...] = 0
numpy_matrix[..., (0, n - 1)] = 0

numpy_time = time.perf_counter() - start_time
print(numpy_matrix)

[[0 0 0 0]
 [0 1 1 0]
 [0 1 1 0]
 [0 0 0 0]]


In [122]:
start_time = time.perf_counter()

custom_matrix = [[1 if (0 < i < n - 1 and 0 < j < n - 1) else 0 for j in range(n)] for i in range(n)]

custom_time = time.perf_counter() - start_time
custom_matrix = np.array(custom_matrix, dtype=int)
print(custom_matrix)

[[0 0 0 0]
 [0 1 1 0]
 [0 1 1 0]
 [0 0 0 0]]


In [123]:
print(f"Numpy time: {round(numpy_time * 1000, 3)} ms.")
print(f"Custom time: {round(custom_time * 1000, 3)} ms.")

Numpy time: 0.247 ms.
Custom time: 0.125 ms.


Вправа 15. Заповнити парні стовпчикі матриці розміром n×n
одиницями, а непарні – нулями.

In [147]:
n = int(input("Enter n: "))

Enter n: 5


In [157]:
start_time = time.perf_counter()

numpy_array =  np.zeros((n, n), dtype=int)
numpy_array[:, 1::2] = 1

numpy_time = time.perf_counter() - start_time
print(numpy_array)

[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]


In [158]:
start_time = time.perf_counter()

custom_matrix = [[1 if j%2 else 0 for j in range(n)] for i in range(n)]
    
custom_time = time.perf_counter() - start_time
custom_matrix = np.array(custom_matrix, dtype=int)
print(custom_matrix)

[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]


In [159]:
print(f"Numpy time: {round(numpy_time * 1000, 3)} ms.")
print(f"Custom time: {round(custom_time * 1000, 3)} ms.")

Numpy time: 0.105 ms.
Custom time: 0.26 ms.


Вправа 16. Заповнити вектор значеннями від 0 до n. Всі значення,
що більші за n/4 та менші за 3n/4 замінити нулями.

In [161]:
n = int(input("Enter n: "))

Enter n: 10


In [165]:
start_time = time.perf_counter()

numpy_array = np.arange(n + 1, dtype=int)
numpy_array[np.logical_and(n / 4 < numpy_array, numpy_array < 3 * n / 4)] = 0

numpy_time = time.perf_counter() - start_time
print(numpy_array)

[ 0  1  2  0  0  0  0  0  8  9 10]


In [166]:
start_time = time.perf_counter()

custom_array = [i for i in range(n + 1)]
custom_array = [0 if (n / 4 < i < 3 * n / 4) else i for i in custom_array]

custom_time = time.perf_counter() - start_time
custom_res = np.array(custom_array, dtype=int)
print(custom_array)

[0, 1, 2, 0, 0, 0, 0, 0, 8, 9, 10]


In [167]:
print(f"Numpy time: {round(numpy_time * 1000, 3)} ms.")
print(f"Custom time: {round(custom_time * 1000, 3)} ms.")

Numpy time: 0.171 ms.
Custom time: 0.201 ms.


Вправа 20. Згенерувати вектор із n випадкових елементів, що
лежать в інтервалі (0,1). Замінити максимальний елемент на 0.

In [168]:
n = int(input("Enter n: "))

Enter n: 5


In [175]:
start_time = time.perf_counter()

numpy_vector = np.random.random(n)
numpy_vector_changed = np.copy(numpy_vector)
max_index = np.argmax(numpy_vector)
numpy_vector_changed[max_index] = 0

numpy_time = time.perf_counter() - start_time
print("Початковий вектор: " + str(numpy_vector))
print("Змінений вектор: " + str(numpy_vector_changed))
print(numpy_vector)

Початковий вектор: [0.56254106 0.03513665 0.63960303 0.15382975 0.05893358]
Змінений вектор: [0.56254106 0.03513665 0.         0.15382975 0.05893358]
[0.56254106 0.03513665 0.63960303 0.15382975 0.05893358]


In [176]:
start_time = time.perf_counter()

castom_vector = [random.random() for _ in range(n)]
castom_vector_changed = castom_vector.copy()

max_value = max(castom_vector_changed)
max_index = castom_vector_changed.index(max_value)
castom_vector_changed[max_index] = 0

custom_time = time.perf_counter() - start_time
custom_res = np.array(custom_array, dtype=int)
print("Початковий вектор: " + str(castom_vector))
print("Змінений вектор: " + str(castom_vector_changed))

Початковий вектор: [0.12791987244231606, 0.14692387165647702, 0.2988207580871509, 0.47809056084509804, 0.5210857807684772]
Змінений вектор: [0.12791987244231606, 0.14692387165647702, 0.2988207580871509, 0.47809056084509804, 0]


In [177]:
print(f"Numpy time: {round(numpy_time * 1000, 3)} ms.")
print(f"Custom time: {round(custom_time * 1000, 3)} ms.")

Numpy time: 0.307 ms.
Custom time: 0.314 ms.
