2. Розв’язати систему алгебраїчних рівнянь за допомогою
формул Крамера і виконати перевірку за допомогою:  
a) матричного множення;  
b) оберненої матриці;  
c) функції numpy.linalg.solve().  
Порівняти всі рішення за допомогою функції numpy.allclose().
\begin{equation}
    \begin{cases}
      x_1 + 2x_2 + x_3 + x_4 = 8\\
      2x_1 + x_2 + x_3 + x_4 = 5\\
      x_1 - x_2 + 2x_3 + x_4 = -1\\
      x_1 + x_2 - x_3 + 3x_4 = 10
    \end{cases}\,
\end{equation}


Метод Крамера: 

In [22]:
import numpy as np

A = [[1, 2, 1, 1], 
     [2, 1, 1, 1], 
     [1, -1, 2,1], 
     [1, 1, -1, 3]]
A = np.array(A)

B = [8, 5, -1, 10]
B = np.array(B)

det = np.linalg.det(A)
n = len(A)

kramer = np.ndarray(n, dtype=np.float64)
for i in range(n):
    K = A.copy()
    K[:, i] = B
    kramer[i] = np.linalg.det(K) / det

print(kramer)

[-0.05263158  2.94736842 -0.15789474  2.31578947]


a) матричне множення

In [23]:
matmul = np.matmul(A, kramer_res)

print(matmul)
print(f"Результати однакові?: {np.allclose(B, matmul_test)}")

[ 8.  5. -1. 10.]
Результати однакові?: True


b) обернена матриця

In [24]:
inversion = np.matmul(np.linalg.inv(A), B)

print(inversion)
print(f"Результати однакові?: {np.allclose(kramer, inversion)}")

[-0.05263158  2.94736842 -0.15789474  2.31578947]
Результати однакові?: True


c) функції numpy.linalg.solve()

In [25]:
linalg = np.linalg.solve(A, B)

print(linalg)
print(f"Результати однакові?: {np.allclose(kramer, linalg)}")

[-0.05263158  2.94736842 -0.15789474  2.31578947]
Результати однакові?: True
